[package]
name = "ethabi"
version = "12.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
homepage = "https://github.com/paritytech/ethabi"
license = "MIT/Apache-2.0"
keywords = ["ethereum", "eth", "abi", "solidity"]
description = "Easy to use conversion of ethereum contract calls to bytecode."
edition = "2018"

[dependencies]
hex = { version = "2.0", package = "rustc-hex" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0.59", default-features = false, features = ["alloc"] }
tiny-keccak = "1.4"
ethereum-types = { version = "0.9.2", default-features = false }
uint = { version = "0.8.2", default-features = false }

[dev-dependencies]
hex-literal = "0.2.1"
paste = "0.1.6"

[badges]
travis-ci = { repository = "paritytech/ethabi", branch = "master" }
coveralls = { repository = "paritytech/ethabi", branch = "master" }

[features]
default = []
std = [
    'uint/std',
    'serde/std',
    'serde_json/std',
    'ethereum-types/std',
]